data API PoC
janeirodigital/sai-impl-web pull request #15
Opened 2022-08-03 17:56 UTC by samurex

Co-authored-by: elf Pavlik <elf-pavlik@hackers4peace.net>

2022-08-03 18:02 UTC, elf-pavlik commented
I see two main advantages of this direction:

1) No need to make up some IriTemplates [example](https://github.com/janeirodigital/sai-impl-web/pull/15/files#diff-1bb1058564acdfb935d41de30e50c39ceedd63f443993cbd15806aeec94c2743L22)
2) Logic responsible for that API could be later moved from backend to frontend and even made that choice configurable per deployment

2022-08-08 18:01 UTC, elf-pavlik commented
Corresponding backend draft PR https://github.com/janeirodigital/sai-impl-service/pull/42

2022-08-10 01:18 UTC, angelaraya requested changes

2022-08-10 01:18 UTC, angelaraya commented on src/app/services/data.service.ts
> +      body: JSON.stringify({type: DataActions.applicationsPanelLoaded.type}),
Do not use the `DataActions` type as it is an internal component of the UI and should not be exposed to the BE or any other component outside of the UI.

We discussed using `MessageType` instead. Another alternative is to just use an object with a const `type` property.

```js
body: JSON.stringify({type: GET_APPLICATIONS})
```
A third shared package where `GET_APPLICATIONS` is defined can be created and shared between any modules that use it to interact with one another.

2022-08-10 01:18 UTC, angelaraya commented on src/app/services/data.service.ts
> +        type: DescActions.descriptionsNeeded.type,
Same as with the `applicationPanelLoaded` scenario above.

2022-08-10 18:27 UTC, elf-pavlik commented
The latest version uses a shared module from the corresponding service draft PR. For now, it relies on running `yarn link` or `npm link` manually.

2022-08-16 16:43 UTC, merged