bootstrapped authorization view
janeirodigital/sai-impl-web pull request #19
Opened 2022-09-06 22:41 UTC by elf-pavlik

can be tested by visiting http://localhost:4200/authorize?client_id=http://localhost:3000/acme/projectron/id

2022-09-07 15:07 UTC, elf-pavlik commented on src/app/components/authorization/authorization.component.ts
> +    // TODO move language into core state?
tracking in #35

2022-09-07 16:30 UTC, angelaraya requested changes

2022-09-07 16:30 UTC, angelaraya commented on src/app/components/redirect-handler/redirect-handler.component.ts
> +        })
```ts
    this.store.select(loggedInStatus).pipe(
      filter((isLoggedIn: boolean) => isLoggedIn),
      switchMap(() => this.store.select(requestedPath)),
      take(1),
    ).subscribe((path: string) => this.router.navigateByUrl(path));
```

Would this an equivalent of what you are going for here?

2022-09-08 01:35 UTC, angelaraya commented on src/app/components/redirect-handler/redirect-handler.component.ts
> +        })
I went down a rabbit hole. And while I still think there are some amount of improvements I think we can merge this now as is.

2022-09-08 01:36 UTC, merged