Language translate - real time - using ngx-translate
janeirodigital/sai-impl-web pull request #55
Opened 2023-01-06 16:18 UTC by mariano-romero-jd

2023-01-06 17:18 UTC, angelaraya requested changes

2023-01-06 17:18 UTC, angelaraya commented on src/app/models/languages.ts
> +export const Languages: Array<any> = [
This file does not belong at /models/. We can have it at the root of the project.

2023-01-06 17:18 UTC, angelaraya commented on src/app/views/navbar/navbar.component.ts
> +  // @Output() selectedLanguage = new EventEmitter<Languages>();
Why the commented out code?

2023-01-06 21:40 UTC, mariano-romero-jd commented on src/app/views/navbar/navbar.component.ts
> +  // @Output() selectedLanguage = new EventEmitter<Languages>();
lines removed

2023-01-06 22:05 UTC, angelaraya approved these changes

2023-01-09 12:10 UTC, elf-pavlik commented
Thank you @mariano-romero-jd , do you still plan to try resolve failing CI or would you prefer that I take a look at it and add a commit to get it to pass?

2023-01-09 17:01 UTC, merged